### PR TITLE
Update for using indigo android app

### PR DESCRIPTION
**Pull request by dwlee**
- Revert `addLayer` from hydro version
- Delete layer NullChecker in `onCreate`

### CODE REVIEW

**Comment by stonier** [comment]
@dwlee this diff is really quite complicated - shouldn't have been more than just a few lines. Any idea why?

**Comment by dwlee** [comment]
I do not know what is exact reason, but I think that this complicated difference is occurred by commit of test code. Anyway, I re-updated from original source.

**Comment by stonier** [comment]
@dwlee this pull request should be going to https://github.com/rosjava/android_core. Can you remake it there?

**Comment by dwlee** [comment]
I moved this issue to https://github.com/rosjava/android_core/pull/237

**Pull request closed without merging**
